CREATE TABLE `emotion_rates`
(
    `id`          INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `happy`       INT UNSIGNED NOT NULL DEFAULT 0,
    `sad`         INT UNSIGNED NOT NULL DEFAULT 0,
    `fear`        INT UNSIGNED NOT NULL DEFAULT 0,
    `disgust`     INT UNSIGNED NOT NULL DEFAULT 0,
    `surprised`   INT UNSIGNED NOT NULL DEFAULT 0,
    `angry`       INT UNSIGNED NOT NULL DEFAULT 0,
    `neutral`     INT UNSIGNED NOT NULL DEFAULT 0,
    `created_at`  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    `updated_at`  TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE `reports`
(
    `id`          INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `user_id`     INT UNSIGNED NOT NULL,
    `content`     TEXT,
    `emotion_rate_id`    INT UNSIGNED NOT NULL,
    `created_at`  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    `updated_at`  TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT `FK_STORY_USER_ID` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`),
    CONSTRAINT `FK_EMOTION_RATE_ID` FOREIGN KEY (`emotion_rate_id`) REFERENCES `emotion_rates` (`id`),
);