CREATE TABLE `users`
(
    `id`          INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `name`        VARCHAR(255) NOT NULL,
    `nickname`    VARCHAR(255) NOT NULL UNIQUE,
    `email`       VARCHAR(255) NOT NULL UNIQUE,
    `password`    VARCHAR(255) NOT NULL,
    `phone`       VARCHAR(100) UNIQUE,
    `created_at`  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    `updated_at`  TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE `locations`
(
    `id`          INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `place_name`  VARCHAR(255) NOT NULL,
    `location`    POINT NOT NULL,
    `created_at`  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    `updated_at`  TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    SPATIAL INDEX(`location`)
);

CREATE TABLE `blooms`
(
    `id`          INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `name`        VARCHAR(255) NOT NULL UNIQUE,
    `type`        VARCHAR(255) NOT NULL,
    `symbol`      VARCHAR(255),
    `created_at`  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    `updated_at`  TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE `emotions`
(
    `id`          INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `type`        VARCHAR(255) NOT NULL,
    `content`     VARCHAR(255),
    `created_at`  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    `updated_at`  TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE `stories`
(
    `id`          INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `user_id`     INT UNSIGNED NOT NULL,
    `title`       VARCHAR(255) NOT NULL,
    `content`     TEXT,
    `likes`       INT UNSIGNED NOT NULL DEFAULT 0,
    `bloom_id`    INT UNSIGNED NOT NULL,
    `emotion_id`  INT UNSIGNED NOT NULL,
    `location`    POINT NOT NULL,
    `created_at`  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    `updated_at`  TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT `FK_STORY_USER_ID` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`),
    CONSTRAINT `FK_STORY_BLOOM_ID` FOREIGN KEY (`bloom_id`) REFERENCES `blooms` (`id`),
    CONSTRAINT `FK_STORY_EMOTION_ID` FOREIGN KEY (`emotion_id`) REFERENCES `emotions` (`id`)
);

CREATE TABLE `story_comments`
(
    `id`          INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `story_id`    INT UNSIGNED NOT NULL,
    `content`     TEXT NOT NULL,
    `created_at`  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    `updated_at`  TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT `FK_STORY_COMMENTS_STORY_ID` FOREIGN KEY (`story_id`) REFERENCES `stories` (`id`)
);

CREATE TABLE `story_images`
(
    `id`          INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `story_id`    INT UNSIGNED NOT NULL,
    `image_url`   VARCHAR(255) NOT NULL,
    `created_at`  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    `updated_at`  TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT `FK_STORY_IMAGES_STORY_ID` FOREIGN KEY (`story_id`) REFERENCES `stories` (`id`)
);
